### ISSUE TITLE
Benchmark de Produtos

### ISSUE THREAD

**Issue by khaueviana** [ListenThen/backend#6]

**Comment by khaueviana** [comment]
Basicamente as ferramentas que encontrei, e peguei referências:

https://www.small-improvements.com/

http://www.qulture.rocks/

http://www.strategymanager.com.br/software-gestao-de-metas/

**Comment by khaueviana** [comment]
@JulianeAlbuquerque

**Comment by khaueviana** [comment]
Todas as ferramentas, basicamente atuam nas principais features que já selecionamos pra aplicação: Feedback 360, OKR e 1:1 Meeting. Com base nisso existe uma gama de relatórios e indicadores.

Coletei a ideia de criarmos algo relacionado a técnica Merit Money do Management 3.0:
https://management30.com/practice/merit-money/

**Comment by JulianeAlbuquerque** [comment]
in English, please!
